---
projectName: googleEarthImageCollector
scriptDirectories:
    pythonDir: C://Python27//
    RDir: C://Program Files//R//R-3.6.1//bin//
    googleEarthDir: C://Program Files//Google//Google Earth Pro//client//
# define UTM crs
projection: +proj=utm +zone=31N, +north +ellps=WGS84 +datum=WGS84 +units=m +no_defs
# define region extent
# lat and lon are UTM Northing and Easting respectively
regionArea:
    latStart: 5711000
    latSize: 2000
    latIntervalSize: 150
    lonStart: 284600
    lonSize: 2000
    lonIntervalSize: 150
cameraOptions:
    horizFov: 50
    range0: 0
    altitudeMode: absolute
    lookAtDuration: 0.1
    zenithAngles: 
    - 0
    - 40
    nSamplesAroundOrigin: 
    - 1
    - 4
    pathLengths: 
    - 550
    - 600
googleEarthOptions:
    GEtimeout: 100000
    maxNumberOfRestarts: 999
#google maps elevation api is used to get rasterised above sea level heights for region
googleMapsOptions:
    #what is the grid resolution of GM heights you want to obtain?
    #heights are collected at this resolution     
    gridResolution: 50
    #extend the region by grid_extent_padding on each region side
    gridExtentPadding: 500
    #what is the final resolution of the raster you want. should be same order of magnitude as 
    #gridResolution_GM (it can be higher res - it is interpolated)
    rasterResFinal: 25
autoMouseClicker:
    useAutoMouseClicker: False
    progFullDir: C:\Users\Roof49\Documents\GitHub\googleEarthImageCollection\bin\MiniMouseMacro.exe
    macroFileName: metaData\mouseMacro\mouse_macro.mmmacro
    #how long does GE approx take to fully load
    google_earth_load_time_s: 45
    #how long does the macro take to run
    autoMouseClicker_time_to_complete_s: 60
...
