---
projectName: googleEarthImageCollector
scriptDirectories:
    pythonDir: C://Python27//
    RDir: C://Program Files//R//R-3.6.1//bin//
    googleEarthDir: C://Program Files//Google//Google Earth Pro//client//
# define UTM crs
projection: +proj=utm +zone=31N, +north +ellps=WGS84 +datum=WGS84 +units=m +no_defs
# define region extent
# lat and lon are UTM Northing and Easting respectively
regionArea:
    latStart: 5712800 
    latSize: 400
    latIntervalSize: 150
    lonStart: 284450
    lonSize: 350
    lonIntervalSize: 150
cameraOptions:
    horizFov: 40
    range0: 0
    altitudeMode: absolute
    lookAtDuration: 0.1
    zenithAngles: 
    - 45
    nSamplesAroundOrigin: 
    - 34
    pathLengths: 
    - 260
googleEarthOptions:
    GEtimeout: 100000
autoMouseClicker:
autoMouseClicker:
    useAutoMouseClicker: False
    progFullDir: C:\Users\micromet\Documents\GitHub\googleEarthImageCollection\bin\MiniMouseMacro.exe
    macroFileName: metaData\mouseMacro\mouse_macro.mmmacro
    #how long does GE approx take to fully load
    google_earth_load_time_s: 15
    #how long does the macro take to run
    autoMouseClicker_time_to_complete_s: 60
...
